receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

processors:
  batch:

exporters:
  debug:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
