entryPoints:
  web:
    address: ":80"  # Listen on HTTP (Cloudflare terminates SSL)
    http:
      redirections:
        entryPoint:
          to: websecure  # Redirect to HTTPS
          scheme: https
  websecure:
    address: ":443"  # Listen on HTTPS

api:
  dashboard: true  # Optional: enable dashboard
  insecure: false  # Needed to point subdomain to the dashboard
  debug: true      # Optional: enable debug mode

log:
  level: "INFO"  # Set to "DEBUG" for more detailed logs

providers:
  rest: {}  # Enable the REST provider to accept dynamic configuration

  docker:
    endpoint: "unix:///var/run/docker.sock"  # Use the Podman socket (Docker-compatible)
    exposedByDefault: false  # Only expose containers that have the correct labels

# TODO Move this to be part of the API Traefik install
certificatesResolvers:
  letsencrypt:
    acme:
      email: "shane@surly.dev"  # Email for Let's Encrypt registration
      storage: "/letsencrypt/acme.json"  # Path to store the ACME certificates
      dnsChallenge:
        provider: "cloudflare"  # Use Cloudflare as the DNS provider for ACME challenge

# metrics:
#   otlp:
#     addEntryPointsLabels: true
#     addRoutersLabels: true
#     addServicesLabels: true
#     pushInterval: "5s"
#     http:
#       endpoint: "http://localhost:4318/v1/metrics"